title: CSSE2 // Polaris Group
description: "August 2023 to June 2024"
owner_name: Xavier Thompson
github_username: XavierTho
github_repo: "CSSE2"
baseurl: "/teacher_portfolio"
future: true
remote_theme: jekyll/minima
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.html
  - 2023-11-27-CSSE-oop-game-levels.md

